config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations'}
  root "welcomes#index"

  resources :welcomes

  resources :users do 
    resources :sellerprofiles
    resources :categories do 
      resources :sub_categories do 
        resources :products
      end
    end
    resources :addresses


    get 'list' , to: "categories#list"
    get 'seller' , to: "welcomes#seller"
    get 'customer' , to: "welcomes#customer"
  end
    get 'category/:category_id/category_sub_category' , to: "welcomes#category_sub_category",  as: "sub_categories"
    get 'category/:category_id/category_sub_category/:sub_category_id' , to: "welcomes#products",  as: "product"
    get 'description_products/:product_id', to: "welcomes#description_products", as: "product_description"
    resources :carts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :category_pic, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category
  has_one_attached :product_cover_pic, dependent: :destroy
  has_many_attached :pictures , dependent: :destroy

  validates :product_name, :brand_name, :product_cover_pic, presence: true
end

app/models/sellerprofile.rb
class Sellerprofile < ApplicationRecord
  belongs_to :user

  validates :name, :trade_licence, :gst_no, :sales_tax, presence: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :cover_pic, dependent: :destroy
  has_many :products, dependent: :destroy


  validates :sub_category_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_one :sellerprofile, dependent: :destroy
  has_many :categories, dependent: :delete_all
  accepts_nested_attributes_for :sellerprofile
  has_many :addresses, dependent: :delete_all
  has_many :sub_categories, dependent: :delete_all

  protected
  def password_required?
    confirmed? ? super : false
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

	before_action :find_address, only: [:new, :create, :edit, :update, :destroy]

	def index
		@addresses = current_user.addresses.all
	end

	def new
		@address = current_user.addresses.new
	end

	def create
		@address = current_user.addresses.create(address_params)
		if @address.save
			redirect_to user_addresses_path(@address)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @address.update(address_params)
			redirect_to user_addresses_path(current_user)
		else
			render 'edit'
		end
	end

	def destroy
		if @address.destroy
			redirect_to user_addresses_path(current_user)
		else
			render 'index'
		end
	end
	
	private

	def find_address
		@address = Address.find_by_id(params[:id])
	end


	def address_params
		params.require(:address).permit(:name, :phone, :street1, :landmark, :city, :state, :country, :zipcode)
	end
		
	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index
		@items = Cart.all
	end

	def create
		@cart = Cart.create(cart_params)
	end

	def destroy
		@cart = Cart.find_by(params[:id])
		respond_to do |format|
	       format.js #-> loads /links/destroy.js.erb
      	end
	end



	private

	def cart_params
		params.require(:cart).permit(:product_id, :amount)
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  def new
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.new
  end

  def create
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.create(product_params)
    if @product.save
      redirect_to user_category_sub_category_path(current_user, @category, @sub_category)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = Product.find_by_id(params[:id])
  end

  def update
    binding.pry
    @product = Product.find_by_id(params[:id])
  end



  private

  def product_params
    params.require(:product).permit(:product_name, :brand_name, :material, :description, :colour, :price, :user_id, :category_id, :product_cover_pic, pictures: [])
  end

end

app/controllers/sellerprofiles_controller.rb
class SellerprofilesController < ApplicationController

  before_action :find_sellerprofile, only: [:create, :edit, :update, :delete]

  def index
    @profile = current_user.build_sellerprofile if current_user.sellerprofile.nil?
  end

  def new 
    #binding.pry
    @profile = current_user.build_sellerprofile
  end

  def create
    @profile = current_user.build_sellerprofile(seller_params)
    if @profile.save
      redirect_to user_sellerprofiles_path(current_user, @profile)
    else
      render 'new'
    end
  end

  def edit
  end


  def show
  end

  def update
    if @profile.update(seller_params)
      redirect_to user_sellerprofiles_path(current_user, @profile)
    else
      render "edit"
    end
  end



  private

  def find_sellerprofile
    @profile = Sellerprofile.find_by_id(params[:id])
  end

  def seller_params
    params.require(:sellerprofile).permit(:name, :contact_no, :phone_no, :fax_no, :street1, :city, :state, :country, :zipcode, :trade_licence, :gst_no, :sales_tax)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  
  def index
  	@categories = Category.all
  end


  def seller
  	@sellers = User.all.where(role: "Seller")
  end

  def customer
  	@customers = User.all.where(role: "Customer")
  end

  def category_sub_category
  	@category = Category.find_by_id(params[:category_id])
  	@sub_category = @category.sub_categories
  end

  def products
  	@sub_category = SubCategory.find_by_id(params[:sub_category_id])
  	@products = @sub_category.products
  end

  def description_products
  	@product = Product.find_by_id(params[:product_id])
  	@cart =  Cart.new
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellerprofiles_helper.rb
module SellerprofilesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/sellerprofiles/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div id="form">
                <%= form_for ([current_user, @profile ])do |form| %>
                    <%= form.label :name %> *
                    <%= form.text_field :name, class: " form-control"%>
                    <%= form.label :contact_no %> *
                    <%= form.text_field :contact_no, class: " form-control"%>
                    <%= form.label :phone_no %> *
                    <%= form.text_field :phone_no, class: " form-control"%>
                    <%= form.label :fax_no %> *
                    <%= form.text_field :fax_no, class: " form-control"%>
                    <%= form.label :street1 %>
                    <%= form.text_field :street1, class: " form-control" %>
                    <%= form.label :landmark %>
                    <%= form.text_field :landmark, class: " form-control" %>
                    <%= form.label :city %>
                    <%= form.text_field :city, class: " form-control" %>
                    <%= form.label :state %>
                    <%= form.text_field :state , class: " form-control"%>
                    <%= form.label :country %>
                    <%= form.text_field :country, class: " form-control" %>
                    <%= form.label :zipcode %>
                    <%= form.text_field :zipcode, class: " form-control" %>
                    <%= form.label :trade_licence %>  *
                    <%= form.text_field :trade_licence, class: " form-control" %>
                    <%= form.label :gst_no %>  *
                    <%= form.text_field :gst_no, class: " form-control" %>
                    <%= form.label :sales_tax %>  *
                    <%= form.text_field :sales_tax, class: " form-control" %><br>
                    <%= form.submit class: "btn btn-success" %>
                <%end%>
                <script type="text/javascript">
                  <%= render "validate.js" %>
                </script>
            </div>
        </div>
    </div>
</div>

app/views/sellerprofiles/_show.html.erb
<br><div class="container">
	<div class="row">
		<div class="col-sm-4">
			<div class="personal_details">
				<h3>Personal Details</h3>
				<b><p>Name</p></b>
				<p><%= current_user.sellerprofile.name %></p>
				<b><p>Email</p></b>
				<p><%= current_user.email %></p>
				<b><p>Contact Number</p></b>
				<p><%= current_user.sellerprofile.contact_no %></p>
				<b><p>Phone Number</p></b>
				<p><%= current_user.sellerprofile.phone_no %></p>
				<b><p>Fax Number</p></b>
				<p><%= current_user.sellerprofile.fax_no %></p>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="account_details">
				<h3>Account Details</h3>
				<b><p>Trade Licence</p></b>
				<p><%= current_user.sellerprofile.trade_licence %></p>
				<b><p>Gst No</p></b>
				<p><%= current_user.sellerprofile.gst_no %></p>
				<b><p>Sales Tax Number</p></b>
				<p><%= current_user.sellerprofile.sales_tax %></p>
			</div>
		</div>
		<div class="col-sm-4">
			<%= link_to "Update Profile", edit_user_sellerprofile_path(current_user, current_user.sellerprofile), class: "btn btn-secondary" %>
		</div>
	</div><br>
	<div class="row"> 
		<div class="col-sm-6">
			<div class="address_details">
				<h3>Address Details</h3>
				<b><p>Street </p></b>
				<p><%= current_user.sellerprofile.street1 %></p>
				<b><p>Landmark</p></b>
				<p><%= current_user.sellerprofile.landmark %></p>
				<b><p>City</p></b>
				<p><%= current_user.sellerprofile.city %></p>
				<b><p>State </p></b>
				<p><%= current_user.sellerprofile.state %></p>
				<b><p>Country</p></b>
				<p><%= current_user.sellerprofile.country %></p>
				<b><p>Zipcode</p></b>
				<p><%= current_user.sellerprofile.zipcode %></p>
			</div>
		</div>
	</div>
</div>

app/views/sellerprofiles/edit.html.erb
<%= render partial: "form", object: @profile %>

app/views/sellerprofiles/index.html.erb
<% if current_user.sellerprofile.name.nil? %>
	<%= render partial: "form", object: @profile %>
<%else%>
	<%= render partial: "show" %>
<%end%>

app/views/sellerprofiles/new.html.erb
<%= render partial: "form", object: @profile %>