config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations'}
  root "welcomes#index"

  resources :welcomes

  resources :users do 
    resources :sellerprofiles
    resources :categories do 
      resources :sub_categories do 
        resources :products
      end
    end
    resources :addresses


    get 'list' , to: "categories#list"
    get 'seller' , to: "welcomes#seller"
    get 'customer' , to: "welcomes#customer"
  end
    get 'category/:category_id/category_sub_category' , to: "welcomes#category_sub_category",  as: "sub_categories"
    get 'category/:category_id/category_sub_category/:sub_category_id' , to: "welcomes#products",  as: "product"
    get 'description_products/:product_id', to: "welcomes#description_products", as: "product_description"
    resources :carts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :category_pic, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category
  has_one_attached :product_cover_pic, dependent: :destroy
  has_many_attached :pictures , dependent: :destroy

  validates :product_name, :brand_name, :product_cover_pic, presence: true
end

app/models/sellerprofile.rb
class Sellerprofile < ApplicationRecord
  belongs_to :user

  validates :name, :trade_licence, :gst_no, :sales_tax, presence: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :cover_pic, dependent: :destroy
  has_many :products, dependent: :destroy


  validates :sub_category_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_one :sellerprofile, dependent: :destroy
  has_many :categories, dependent: :delete_all
  accepts_nested_attributes_for :sellerprofile
  has_many :addresses, dependent: :delete_all
  has_many :sub_categories, dependent: :delete_all

  protected
  def password_required?
    confirmed? ? super : false
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

	before_action :find_address, only: [:new, :create, :edit, :update, :destroy]

	def index
		@addresses = current_user.addresses.all
	end

	def new
		@address = current_user.addresses.new
	end

	def create
		@address = current_user.addresses.create(address_params)
		if @address.save
			redirect_to user_addresses_path(@address)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @address.update(address_params)
			redirect_to user_addresses_path(current_user)
		else
			render 'edit'
		end
	end

	def destroy
		if @address.destroy
			redirect_to user_addresses_path(current_user)
		else
			render 'index'
		end
	end
	
	private

	def find_address
		@address = Address.find_by_id(params[:id])
	end


	def address_params
		params.require(:address).permit(:name, :phone, :street1, :landmark, :city, :state, :country, :zipcode)
	end
		
	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index
		@items = Cart.all
	end

	def create
		@cart = Cart.create(cart_params)
	end

	def destroy
		@cart = Cart.find_by(params[:id])
		respond_to do |format|
	       format.js #-> loads /links/destroy.js.erb
      	end
	end



	private

	def cart_params
		params.require(:cart).permit(:product_id, :amount)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = current_user.categories.create(category_params)
      if @category.save
          redirect_to user_categories_path(current_user)
      else
          render "new"
      end
    end

    def show
      @category = Category.find_by_id(params[:id])
      @sub_categories = @category.sub_categories.all
    end

    def edit
      @category = Category.find_by_id(params[:id])
    end

    def update
      @category = Category.find_by_id(params[:id])
      if @category.update(category_params)
        redirect_to user_list_path(current_user)
      else
        render 'edit'
      end
    end

    def destroy
      @category = Category.find_by_id(params[:id])
      if @category.destroy
        redirect_to user_list_path(current_user)
      end

    end

    def list
      @categories = current_user.categories
    end
            
    private
    def category_params
      params.require(:category).permit(:name, :category_pic)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  def new
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.new
  end

  def create
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.create(product_params)
    if @product.save
      redirect_to user_category_sub_category_path(current_user, @category, @sub_category)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = Product.find_by_id(params[:id])
  end

  def update
    binding.pry
    @product = Product.find_by_id(params[:id])
  end



  private

  def product_params
    params.require(:product).permit(:product_name, :brand_name, :material, :description, :colour, :price, :user_id, :category_id, :product_cover_pic, pictures: [])
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  
  def index
  	@categories = Category.all
  end


  def seller
  	@sellers = User.all.where(role: "Seller")
  end

  def customer
  	@customers = User.all.where(role: "Customer")
  end

  def category_sub_category
  	@category = Category.find_by_id(params[:category_id])
  	@sub_category = @category.sub_categories
  end

  def products
  	@sub_category = SubCategory.find_by_id(params[:sub_category_id])
  	@products = @sub_category.products
  end

  def description_products
  	@product = Product.find_by_id(params[:product_id])
  	@cart =  Cart.new
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellerprofiles_helper.rb
module SellerprofilesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/carts/_items.html.erb
<%@items.each do |item| %>
	<tr>
		<td> <%= image_tag(item.product.product_cover_pic, width: "100", height: "80")%> <b><%= link_to item.product.product_name, product_description_path(item.product_id)%></b>,&nbsp;&nbsp;(<%= item.product.brand_name%>,&nbsp;&nbsp;<%= item.product.material%>,&nbsp;&nbsp;<%= item.product.description%>,&nbsp;&nbsp;<%= item.product.colour%>)</td>
		<td><b><%= item.product.price%></b></td>
		<td><%#= link_to "Remove", cart_path(item), method: :delete %></td>
	</tr>
<%end%>

app/views/carts/destroy.js.erb
destroy.js.erb

app/views/carts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<table class="table"> <h2>Shopping Cart</h2>
				<tr>
					<th>Products</th>
					<th>Price</th>
				</tr><br>
				<tbody class="cart_item">
					<%= render "items"%>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/categories/_form.html.erb
<div class="container"><br>
	<div class="row">
		<div class="col-sm-4">
			<%= form_for ([current_user, @category]) do  |form| %>
				<%= form.label :name %>
				<%= form.text_field :name, class: "form-control" %><br>
				<%= form.label :category_pic %>
				<%= form.file_field :category_pic, class: "form-control" %><br>
				<%= form.submit class: "btn btn-success" %>
				<%= link_to "Back", user_categories_path(current_user), class: "btn btn-warning" %>
			<%end%>
		</div>
	</div>
</div>

app/views/categories/edit.html.erb
<%= render partial: "form", object: @category %>

app/views/categories/index.html.erb
<div class="container"><br>
  <div class="row">
    <% @categories.each do |category|%> 
      <div class="col-sm-4">
          <div class="card" style="width: 22rem;">
            <%= link_to image_tag(category.category_pic,  width: "350", height: "250"), user_category_path(current_user, category) %>
            <div class="card-body">
              <center><h5 class="card-title"><%= link_to category.name, user_category_path(current_user, category), class: "nav-link"%></h5></center>
            </div>
            <%if current_user.role == "System Admin"%>
              <%= link_to "Edit", edit_user_category_path(category.user_id, category), class: "btn btn-warning "%> &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Delete", user_category_path(category.user_id, category), class: "btn btn-danger ", method: :delete%>
            <%end%>
          </div>
      </div>
    <%end%>
  </div>
</div>

<% if current_user.role.nil? %>
  <%= link_to "Add new Category", new_user_category_path(current_user), class: "btn btn-primary" %> 
<%end%>

app/views/categories/list.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<table class="table">
				<tr>
					<th>Category Name</th>
					<th>Edit</th>
					<th>Delete</th>

				</tr>
				<% @categories.each do |category| %>
					<tr>
						<th><%= category.name %></th>
						<th><%= link_to "Edit", edit_user_category_path(current_user, category) %></th>
						<th><%= link_to "Delete", user_category_path(current_user, category), method: :delete %></th>
					</tr>
				<%end%>
			</table>
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<%= render partial: "form", object: @category %>

app/views/categories/show.html.erb
<div class="container"><br><br>
  <div class="row">
    <% @sub_categories.each do |sub_category|%>
      <div class="col-sm-3">
        <div class="card" style="width: 16rem;">
          <div class="card-body">
            <%=link_to image_tag(sub_category.cover_pic, width: "210", height: "200"), user_category_sub_category_path(sub_category.user_id, sub_category.category_id, sub_category)%><br><br>
            <center><h5 class="card-title"><%= link_to sub_category.sub_category_name, class: "nav-link" %></h5></center>
          </div>
          <% if current_user.role == "System Admin" %>
            <%= link_to "Edit", edit_user_category_sub_category_path(sub_category.user_id, sub_category.category_id, sub_category), class: "btn btn-warning "%> &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Delete", "#", class: "btn btn-danger "%>
          <%end%>
        </div>
      </div>
    <%end%>
  </div> <br><br>
  <div class="row">
    <div class="col-sm-12">
      <% if current_user.role == "System Admin" %>
        <%= link_to "Add new Category", new_user_category_sub_category_path(@category.user_id, @category), class: "btn btn-primary", data: {toggle: "modal", target: "#modelforsubcategory"} %>
      <%end%>
      <%= link_to "Back", user_categories_path(@category.user_id), class: "btn btn-warning" %>
      
    </div>
  </div> 
</div>
<div class="modal fade" id="modelforsubcategory" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for ([current_user, @category, @category.sub_categories.new]) do |form| %>
          <%= form.label :sub_category_name %>
          <%= form.text_field :sub_category_name, class: "form-control"%><br>
          <%= form.hidden_field :user_id, value: @category.user_id %>
          <%= form.label :cover_pic%>
          <%= form.file_field :cover_pic %><br>
      </div>
          
      <div class="modal-footer">
        <div class="actions">
          <%= form.submit class: "btn btn-success" %>
        </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<%= form_for :product, url: {controller: "products", action: :create}, html: {id: "product_for"} do |form|%>
				<%= form.label :product_name %>
				<%= form.text_field :product_name, class: "form-control" %><br>
				<%= form.label :brand_name %>
				<%= form.text_field :brand_name, class: "form-control" %><br>
				<%= form.label :material %>
				<%= form.text_field :material, class: "form-control" %><br>
				<%= form.label :description %>
				<%= form.text_field :description, class: "form-control" %><br>
				<%= form.label :colour %>
				<%= form.text_field :colour, class: "form-control" %><br>
				<%= form.label :price %>
				<%= form.text_field :price, class: "form-control" %><br>
				<%= form.label :cover_pic %>
				<%= form.file_field :product_cover_pic, class: "form-control" %><br>
				<%= form.label :pictures %>
				<%= form.file_field :pictures, multiple: true, class: "form-control" %>
				<%= form.hidden_field :user_id, value: @sub_category.user_id %>
				<%= form.hidden_field :category_id, value: @sub_category.category_id  %><br>
				<%= form.submit class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "Back", user_category_sub_category_path(@sub_category.user_id, @sub_category.category_id, @sub_category), class: "btn btn-warning" %>
			<%end%>
			<script type="text/javascript">
                  <%= render "validate.js" %>
            </script>
		</div>
	</div>
</div>











			

app/views/products/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<%= form_for :product, html: {id: "product_for"}, method: :update do |form|%>
				<%= form.label :product_name %>
				<%= form.text_field :product_name, class: "form-control" %><br>
				<%= form.label :brand_name %>
				<%= form.text_field :brand_name, class: "form-control" %><br>
				<%= form.label :material %>
				<%= form.text_field :material, class: "form-control" %><br>
				<%= form.label :description %>
				<%= form.text_field :description, class: "form-control" %><br>
				<%= form.label :colour %>
				<%= form.text_field :colour, class: "form-control" %><br>
				<%= form.label :cover_pic %>
				<%= form.file_field :product_cover_pic, class: "form-control" %><br>
				<%= form.label :pictures %>
				<%= form.file_field :pictures, multiple: true, class: "form-control" %>
				<%= form.hidden_field :user_id, value: @sub_category.user_id %>
				<%= form.hidden_field :category_id, value: @sub_category.category_id  %><br>
				<%= form.submit class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "Back", user_category_sub_category_path(@sub_category.user_id, @sub_category.category_id, @sub_category), class: "btn btn-warning" %>
			<%end%>
			<script type="text/javascript">
                  <%= render "validate.js" %>
            </script>
		</div>
	</div>
</div>

app/views/products/new.html.erb
<%= render partial: "form" ,object: @product %>

app/views/products/show.html.erb
<div class="container"><br>
  <div class="row">
    <div class="col-sm-4", id="cover_picture">
      <div class="cover_picture"><br>
        <%= image_tag(@product.product_cover_pic, width: "320", height: "280") %>
      </div><br><br>
    </div>&nbsp;&nbsp;&nbsp;&nbsp;<br><br>
    <div class="col-sm-4">
      <div class="product_details">
        <b>Product Name</b> - <%= @product.product_name%><br><br>
        <b>Brand Name</b> - <%= @product.brand_name%><br><br>
        <b>Material</b> - <%= @product.material %><br><br>
        <b>Description</b> - <%= @product.description %> <br><br>
        <b>Colour</b> - <%= @product.colour %><br><br>
      </div>
    </div>
  </div>

  <br><br><br><%= link_to "Back", user_category_sub_category_path(current_user, @product.category_id, @product.sub_category_id), class: "btn btn-warning" %>
</div>