config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations'}
  root "welcomes#index"

  resources :welcomes

  resources :users do 
    resources :sellerprofiles
    resources :categories do 
      resources :sub_categories do 
        resources :products
      end
    end
    resources :addresses


    get 'list' , to: "categories#list"
    get 'seller' , to: "welcomes#seller"
    get 'customer' , to: "welcomes#customer"
  end
    get 'category/:category_id/category_sub_category' , to: "welcomes#category_sub_category",  as: "sub_categories"
    get 'category/:category_id/category_sub_category/:sub_category_id' , to: "welcomes#products",  as: "product"
    get 'description_products/:product_id', to: "welcomes#description_products", as: "product_description"
    resources :carts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :category_pic, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category
  has_one_attached :product_cover_pic, dependent: :destroy
  has_many_attached :pictures , dependent: :destroy

  validates :product_name, :brand_name, :product_cover_pic, presence: true
end

app/models/sellerprofile.rb
class Sellerprofile < ApplicationRecord
  belongs_to :user

  validates :name, :trade_licence, :gst_no, :sales_tax, presence: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :cover_pic, dependent: :destroy
  has_many :products, dependent: :destroy


  validates :sub_category_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_one :sellerprofile, dependent: :destroy
  has_many :categories, dependent: :delete_all
  accepts_nested_attributes_for :sellerprofile
  has_many :addresses, dependent: :delete_all
  has_many :sub_categories, dependent: :delete_all

  protected
  def password_required?
    confirmed? ? super : false
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

	before_action :find_address, only: [:new, :create, :edit, :update, :destroy]

	def index
		@addresses = current_user.addresses.all
	end

	def new
		@address = current_user.addresses.new
	end

	def create
		@address = current_user.addresses.create(address_params)
		if @address.save
			redirect_to user_addresses_path(@address)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @address.update(address_params)
			redirect_to user_addresses_path(current_user)
		else
			render 'edit'
		end
	end

	def destroy
		if @address.destroy
			redirect_to user_addresses_path(current_user)
		else
			render 'index'
		end
	end
	
	private

	def find_address
		@address = Address.find_by_id(params[:id])
	end


	def address_params
		params.require(:address).permit(:name, :phone, :street1, :landmark, :city, :state, :country, :zipcode)
	end
		
	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index
		@items = Cart.all
	end

	def create
		@cart = Cart.create(cart_params)
	end

	def destroy
		@cart = Cart.find_by(params[:id])
		respond_to do |format|
	       format.js #-> loads /links/destroy.js.erb
      	end
	end



	private

	def cart_params
		params.require(:cart).permit(:product_id, :amount)
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  def new
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.new
  end

  def create
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.create(product_params)
    if @product.save
      redirect_to user_category_sub_category_path(current_user, @category, @sub_category)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = Product.find_by_id(params[:id])
  end

  def update
    binding.pry
    @product = Product.find_by_id(params[:id])
  end



  private

  def product_params
    params.require(:product).permit(:product_name, :brand_name, :material, :description, :colour, :price, :user_id, :category_id, :product_cover_pic, pictures: [])
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  
  def index
  	@categories = Category.all
  end


  def seller
  	@sellers = User.all.where(role: "Seller")
  end

  def customer
  	@customers = User.all.where(role: "Customer")
  end

  def category_sub_category
  	@category = Category.find_by_id(params[:category_id])
  	@sub_category = @category.sub_categories
  end

  def products
  	@sub_category = SubCategory.find_by_id(params[:sub_category_id])
  	@products = @sub_category.products
  end

  def description_products
  	@product = Product.find_by_id(params[:product_id])
  	@cart =  Cart.new
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellerprofiles_helper.rb
module SellerprofilesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/addresses/_form.html.erb
<div class="container"><br>
	<div class="row">
		<div class="col-cm-6">
			<%= form_for ([current_user, @address]) do |form|%>
				<%= form.label :name %>
				<%= form.text_field :name, class: "form-control" %><br>
				<%= form.label :phone %>
				<%= form.text_field :phone, class: "form-control"  %><br>
				<%= form.label :street1 %>
				<%= form.text_field :street1, class: "form-control"  %><br>
				<%= form.label :landmark %>
				<%= form.text_field :landmark, class: "form-control"  %><br>
				<%= form.label :city %>
				<%= form.text_field :city, class: "form-control"  %><br>
				<%= form.label :state %>
				<%= form.text_field :state, class: "form-control"  %><br>
				<%= form.label :country %>
				<%= form.text_field :country, class: "form-control"  %><br>
				<%= form.label :zipcode %>
				<%= form.text_field :zipcode, class: "form-control"  %><br>
				<%= form.submit class: "btn btn-success"  %> 
			<%end%>
		</div>
	</div>
</div>

app/views/addresses/edit.html.erb
<%= render partial: "form", object: @address %>

app/views/addresses/index.html.erb
<div class="container"><br>
	<div class="row">
		<% @addresses.each do |address| %>
			<div class="col-sm-4">
				<div class="card" style="width: 18rem;">
				  <div class="card-body">
				    <h5 class="card-title"><%= address.name %></h5>
				    <b>Street - </b><%= address.street1%><br>
				    <b>Landmark - </b><%= address.landmark%><br>
				    <b>City - </b><%= address.city%><br>
				    <b>State - </b><%= address.state%><br>
				    <b>Country - </b><%= address.country%><br>
				    <b>Zipcode - </b> <%= address.zipcode%><br><br>	
				    <%= link_to "Edit", edit_user_address_path(current_user, address), class: "btn btn-warning"%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Delete", user_address_path(current_user, address), method: :delete, class: "btn btn-danger"%>
				  </div>
				</div>
			</div><br>
		<%end%>
	</div><br>
	<div class="row">
		<div class="col-sm-10">
			<%= link_to "Add Address", new_user_address_path(current_user), class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/addresses/new.html.erb
<%= render partial: "form", object: @address %>

app/views/welcomes/category_sub_category.html.erb
<div class="container"><br>
	<div class="row">
		<%@sub_category.each do |subcategory| %>
			<div class="col-sm-4">
				<div class="card" style="width: 18rem;">
				  <%= link_to image_tag(subcategory.cover_pic, width: "285", height: "250"), product_path(subcategory.category_id, subcategory)%>
				  <div class="card-body">
				    <center><b><%= subcategory.sub_category_name %></b></center>
				  </div>
				</div>
			</div>
		<%end%>
	</div>
</div>


	

app/views/welcomes/customer.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-2">
			<table class="table">
				<tr>
					<th>Customer Email</th>
				</tr>
				<% @customers.each do |customer| %>
				<tr>
					<td><%= customer.email %></td>
				</tr>
				<%end%>
			</table>
		</div>
	</div>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Back", welcomes_index_path, class: "btn btn-warning" %>

app/views/welcomes/description_products.html.erb
<div class="container"><br>
  <div class="row">
    <div class="col-sm-4" id="cover_picture">
      <div class="cover_picture"><br>
        <%= image_tag(@product.product_cover_pic, width: "320", height: "280") %>
      </div><br><br>
    </div>&nbsp;&nbsp;&nbsp;&nbsp;<br><br>
    <div class="col-sm-4">
      <div class="product_details">
        <span class="product_name"><b>Product Name</b> - <%= @product.product_name%><br><br></span>
        <span class="product_brand"><b>Brand Name</b> - <%= @product.brand_name%><br><br></span>
        <span class="product_material"><b>Material</b> - <%= @product.material %><br><br></span>
        <span class="product_description"><b>Description</b> - <%= @product.description %> <br><br></span>
        <span class="product_colour"><b>Colour</b> - <%= @product.colour %><br><br></span>
        <span class="a-price-symbol">₹</span>&nbsp;
        <span class= "product_price"> <%= @product.price %></span>
      </div>
    </div>
    <div class="col-sm-3">
    	<div class="booking_div">
    		<%= form_for @cart, remote: :true do |form| %>
    			<%= form.hidden_field :amount, value: @product.price, class: "form-control" %><br>
    			<%= form.hidden_field :product_id, value: @product.id, class: "form-control" %><br>
    			<span>
    				<%= form.submit "Add to Cart", class: "add_cart" %>
    			</span><br><br><br>
    		<%end%>
    			<span class= "buy_now" ><%= link_to "Buy Now", "#" %></span>
    	</div>
    </div>
  </div>

</div>

app/views/welcomes/index.html.erb
<div class="container">
	<div class="row">
		<% @categories.each do |category| %>
			<div class="col-sm-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<div class="card" style="width: 22rem;">
				  <%= link_to image_tag(category.category_pic,  width: "350", height: "250"), sub_categories_path(category.id)%>
				  <div class="card-body">
				    <center><b><p class="card-text"><%= category.name%></p></b></center>
				  </div>
				</div>
			</div>
		<%end%>
	</div>
</div>

app/views/welcomes/products.html.erb
<div class="container"><br>
    <div class="row">
        <% @products.each do |product|%>
            <div class="col-sm-3" >&nbsp;&nbsp;&nbsp;
                <div class="conpoment" id="product_div">
                    <%= link_to image_tag(product.product_cover_pic, class: "cover_img", width: "255", height: "200"), product_description_path(product.id)%>    
                </div>
                <div class="product_details"><br>
                    <span class="product_name"><%= product.product_name %><br></span>
                    <span class="a-price-symbol">₹</span>&nbsp;
                    <span class="product_price"><%= product.price%></span>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/welcomes/seller.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-2">
			<table class="table">
				<tr>
					<th>User Email</th>
				</tr>
				<% @sellers.each do |seller| %>
				<tr>
					<td><%= seller.email %></td>
				</tr>
				<%end%>
			</table>
		</div>
	</div>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Back", welcomes_index_path, class: "btn btn-warning" %>