config/routes.rb
Rails.application.routes.draw do
  get 'welcomes/index'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations'}
  root "welcomes#index"

  resources :welcomes

  resources :users do 
    resources :sellerprofiles
    resources :categories do 
      resources :sub_categories do 
        resources :products
      end
    end
    resources :addresses


    get 'list' , to: "categories#list"
    get 'seller' , to: "welcomes#seller"
    get 'customer' , to: "welcomes#customer"
  end
    get 'category/:category_id/category_sub_category' , to: "welcomes#category_sub_category",  as: "sub_categories"
    get 'category/:category_id/category_sub_category/:sub_category_id' , to: "welcomes#products",  as: "product"
    get 'description_products/:product_id', to: "welcomes#description_products", as: "product_description"
    resources :carts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :category_pic, dependent: :destroy
  has_many :sub_categories, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category
  has_one_attached :product_cover_pic, dependent: :destroy
  has_many_attached :pictures , dependent: :destroy

  validates :product_name, :brand_name, :product_cover_pic, presence: true
end

app/models/sellerprofile.rb
class Sellerprofile < ApplicationRecord
  belongs_to :user

  validates :name, :trade_licence, :gst_no, :sales_tax, presence: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :cover_pic, dependent: :destroy
  has_many :products, dependent: :destroy


  validates :sub_category_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_one :sellerprofile, dependent: :destroy
  has_many :categories, dependent: :delete_all
  accepts_nested_attributes_for :sellerprofile
  has_many :addresses, dependent: :delete_all
  has_many :sub_categories, dependent: :delete_all

  protected
  def password_required?
    confirmed? ? super : false
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index
		@items = Cart.all
	end

	def create
		@cart = Cart.create(cart_params)
	end

	def destroy
		@cart = Cart.find_by(params[:id])
		respond_to do |format|
	       format.js #-> loads /links/destroy.js.erb
      	end
	end



	private

	def cart_params
		params.require(:cart).permit(:product_id, :amount)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  def new
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.new
  end

  def create
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = @sub_category.products.create(product_params)
    if @product.save
      redirect_to user_category_sub_category_path(current_user, @category, @sub_category)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @sub_category = SubCategory.find_by_id(params[:sub_category_id])
    @product = Product.find_by_id(params[:id])
  end

  def update
    binding.pry
    @product = Product.find_by_id(params[:id])
  end



  private

  def product_params
    params.require(:product).permit(:product_name, :brand_name, :material, :description, :colour, :price, :user_id, :category_id, :product_cover_pic, pictures: [])
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  
  def index
  	@categories = Category.all
  end


  def seller
  	@sellers = User.all.where(role: "Seller")
  end

  def customer
  	@customers = User.all.where(role: "Customer")
  end

  def category_sub_category
  	@category = Category.find_by_id(params[:category_id])
  	@sub_category = @category.sub_categories
  end

  def products
  	@sub_category = SubCategory.find_by_id(params[:sub_category_id])
  	@products = @sub_category.products
  end

  def description_products
  	@product = Product.find_by_id(params[:product_id])
  	@cart =  Cart.new
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellerprofiles_helper.rb
module SellerprofilesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_header.html.erb
<% if current_user.present? %>
	<% if current_user.role == "Customer" %>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <%= link_to "Habiliment Store", welcomes_path, :class => "navbar-brand" %>
		    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
		      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
		        <li class="nav-item <%= 'active' if params[:controller] == 'welcomes' %>">
		          <%= link_to "Home", welcomes_path, :class => "nav-link" %>
		        </li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'club' %>">
		            <%= link_to "Buy", "#", class: "nav-link"  %></li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'guest_user' %>">
		            <%= link_to "Profile", user_addresses_path(current_user), class: "nav-link"  %></li>
		          <li class = "nav-item" ></li>
		      </ul>
		      <ul class="navbar-nav">
		        <% if current_user.present? %>
		        	<%= link_to '<i class="fas fa-cart-arrow-down" style="font-size:20px"></i>'.html_safe, "#", class: "nav-link"%>
		          <li><%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete, data: {confirm:"Are you Sure"} %></li>
		        <%else%>
		          <li><%= link_to 'Sign In', new_user_session_path, :class => "nav-link" %></li>
		        <%end%>
		      </ul>
		    </div>
		</nav>
	<%elsif current_user.role == "Seller"%> 
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <%= link_to "Habiliment Store", welcomes_path, :class => "navbar-brand" %>
		    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
		      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
		        <li class="nav-item <%= 'active' if params[:controller] == 'welcomes' %>">
		          <%= link_to "Home", welcomes_path, :class => "nav-link" %>
		        </li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'club' %>">
		          	<%= link_to "Profile", user_sellerprofiles_path(current_user), :class => "nav-link" %>
		        	</li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'guest_user' %>">
		            <%= link_to "Categories", user_categories_path(current_user), class: "nav-link"  %></li>
		          <li class = "nav-item" ></li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'guest_user' %>">
		            <%= link_to "Lists", user_list_path(current_user), class: "nav-link"  %></li>
		          <li class = "nav-item" ></li>
		      </ul>
		      <ul class="navbar-nav">
		        <% if current_user.present? %>
		        	<%= link_to '<i class="fas fa-cart-arrow-down" style="font-size:20px"></i>'.html_safe, "#", class: "nav-link"%>
		          <li><%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete, data: {confirm:"Are you Sure"} %></li>
		        <%else%>
		          <li><%= link_to 'Sign In', new_user_session_path, :class => "nav-link" %></li>
		        <%end%>
		      </ul>
		    </div>
		</nav>
	<%elsif current_user.role == "System Admin"%> 
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <%= link_to "Habiliment Store", welcomes_path, :class => "navbar-brand" %>
		    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
		      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
		        <li class="nav-item <%= 'active' if params[:controller] == 'welcomes' %>">
		          <%= link_to "Home", welcomes_path, :class => "nav-link" %>
		        </li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'club' %>">
		            <%= link_to "Sellers", user_seller_path(current_user), class: "nav-link"  %></li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'guest_user' %>">
		            <%= link_to "Customers", user_customer_path(current_user), class: "nav-link"  %></li>
		          <li class = "nav-item" ></li>
		          <li class="nav-item <%= 'active' if params[:controller] == 'guest_user' %>">
		            <%= link_to "Categories", user_categories_path(current_user), class: "nav-link"  %></li>
		          <li class = "nav-item" ></li>
		      </ul>
		      <ul class="navbar-nav">
		        <% if current_user.present? %>
		        	<%= link_to '<i class="fas fa-cart-arrow-down" style="font-size:20px"></i>'.html_safe, "#", class: "nav-link"%>
		          <li><%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete, data: {confirm:"Are you Sure"} %></li>
		        <%else%>
		          <li><%= link_to 'Sign In', new_user_session_path, :class => "nav-link" %></li>
		        <%end%>
		      </ul>
		    </div>
		</nav>
	<%end%>
<%else%>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
	  <%= link_to "Habiliment Store", welcomes_path, :class => "navbar-brand" %>
	    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
	      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	        <li class="nav-item <%= 'active' if params[:controller] == 'welcomes' %>">
	          <%= link_to "Home", welcomes_path, :class => "nav-link" %>
	        </li>
	      </ul>
	      <ul class="navbar-nav">
	      	<%= link_to '<i class="fas fa-cart-arrow-down" style="font-size:20px"></i>'.html_safe, carts_path, class: "nav-link"%>
	        	<li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          Registration
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			          <%= link_to "Customer", new_user_registration_path(role: "Customer"), class: "dropdown-item" %>
			          <%= link_to "Seller", new_user_registration_path(role: "Seller"), class: "dropdown-item" %>
			        </div>
			      </li>
	          <li><%= link_to 'Login', new_user_session_path, :class => "nav-link", data: {toggle: "modal", target: "#exampleModal"} %></li>
	      </ul>
	    </div>
	</nav>
<%end%>



<!-- Login Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
				  <div class="field">
				    <%= f.label :email %><br />
				    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control"%>
				  </div>

				  <div class="field">
				    <%= f.label :password %><br />
				    <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
				  </div>

				  <% if devise_mapping.rememberable? %>
				    <div class="field"><br>
				      <%= f.check_box :remember_me %>
				      <%= f.label :remember_me %>
				    </div>
				  <% end %>
			</div>
      <div class="modal-footer">
         <div class="actions">
				    <%= f.submit "Log in", class: "btn btn-success" %>
				  </div>
				<% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habiliments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>